spring:
  application:
    name: TransactionService

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver